### ISSUE TITLE
Doesn't work on 3DS anymore?

### ISSUE THREAD

**Issue by Szprinktrap** [corbindavenport/imageshare#14]
As the title says. I tried to use ImageShare on a 3DS, but i was greeted with error code 032-1035 for some reason.
![photo_2022-10-26_11-47-26](https://user-images.githubusercontent.com/29673535/197994605-749b3072-5a95-4e15-8764-a2c1bbadb38d.jpg)

**Comment by corbindavenport** [comment]
I'm getting the same thing, and someone else mentioned it's broken on Wii U (where I think it was working before now). It looks like some root certificates for the 3DS Browser might have expired, including the one DigitalOcean uses. Not sure what the fix is yet.

**Comment by corbindavenport** [comment]
This should be fixed now, I've migrated ImageShare to a VPS without forced HTTPS. It should now work on all browsers by using `http://theimageshare.com` instead of `https://`. I'll add a message to the web app.
