### ISSUE TITLE
[Suggestion] Replacing imgur with another Imagehost

### ISSUE THREAD

**Issue by jessienab** [corbindavenport/imageshare#17]
Imgur recently [announced their plans](**url**) to delete "old, unused, and inactive content". In this case, uploading images using Imageshare to Imgur longer term may not be a good idea, as that content could in theory be lost later on down.

It seems the code is simple enough to switch to another API, but I don't want to recommend any specific one; this is more of a notice than an actual "issue", especially if users consider the images sent to imageshare as ephemeral.

Thank you for this service and code!

**Comment by corbindavenport** [comment]
Marking this as closed because the latest update fully supports both Imgur and ImgBB: https://blog.corbin.io/post/739426697614639104/the-new-imageshare
