### ISSUE TITLE
Node.js Rewrite

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/imageshare#28]
ImageShare is currently in the process of being rewritten as a Node.js server, replacing the original PHP codebase. The current version relies on external third-party services for image uploads and QR code generation, and the code is getting pretty messy. The work is currently being done in the `node-rewrite` branch.

### Project Goals
- Image uploads are handled entirely by the ImageShare server, without Imgur or ImgBB
- QR code images are generated by ImageShare server, not the [goQR.me API](https://goqr.me/api/)
- Cleaner code with simplified Docker container structure
- Improved documentation and installation for self-hosting
- Seamless upgrade from previous PHP version
- Still compatible with Nintendo 3DS, Wii U, and other legacy web browsers

### Project Status
Most features in the current version will be ported to the new Node version, if not all features. The live site will be switched to the new codebase when the core functionality is available.

**Current features that need to be implemented:**
- [x] Basic web interface with two-column layout and 3DS-specific viewport fixes
- [x] Favicon and home screen app icons
- [x] Optional HTTPS support
- [x] Docker container
- [x] Optional Plausible analytics support
- [x] QR code for viewing uploaded image on another device
- [x] Clickable link for viewing uploaded image
- [x] Game title detection for 3DS games
- [x] Web app manifest for standalone mode on supported browsers
- [x] Compatibility with existing Docker configuration settings (as explained in `DEV.md`)
- [x] Error handling with rendered web pages

**New changes and features:**
- [x] Uploading images with temporary server hosting
- [x] Configurable upload size limit (previously #21)
- [x] Image is downloaded immediately after scanning with [Content-Disposition HTTP header](https://modfoss.com/force-download-with-http-headers.html)
- [x] Wii U game detection
- [x] Game title is added to downloaded image
- [x] Update setup documentation
- [x] Support for all image and video formats
- [x] Create temporary short link for typing on another device
- [x] Dark mode support
- [x] Improved design with better legacy browser support

**Comment by wanniethecharacter** [comment]
Bring back ImgBB!

**Comment by wanniethecharacter** [comment]
> Bring back ImgBB!

and by that, I mean the option to switch from its own server to ImgBB so my photos won’t get deleted after 2 minutes!

**Comment by corbindavenport** [comment]
@wanniethecharacter I'm still figuring out if ImgBB and/or Imgur support will be added back as options. They've been pretty unreliable over the past few years, which is why the current focus is transferring images to a modern device with the QR code or link (the link needs to be improved for sure). Once the images are on another device they can be backed up or uploaded anywhere.

The [ImgBB website](https://imgbb.com/) now lists API access as a paid feature, so I'm not sure how much longer it will be available for free, and it was rate-limiting API requests from the main site (not sure if that applied to custom keys or just the default public key). Imgur blocked the main site entirely so the API was only usable by people self-hosting.

**Comment by corbindavenport** [comment]
Imgur and ImgBB support won't be implemented in the new version. I made a new issue for that discussion and possible return in the future: #31

**Comment by corbindavenport** [comment]
It's done! 🎊
